[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/generador"
  to = "/generador.html"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/auth-callback.html"
  status = 200
